"""add topic hierarchy for learning outcomes

Revision ID: 27c71b85bd07
Revises: acce85c8816e
Create Date: 2026-08-06 22:49:33.938747

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27c71b85bd07'
down_revision = 'acce85c8816e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_topic_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'topics', ['parent_topic_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topics', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('parent_topic_id')

    # ### end Alembic commands ###
