"""add subscriptions table and free_turns_used

Revision ID: 8192c7252875
Revises: 27c71b85bd07
Create Date: 2026-08-07 20:45:55.892905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8192c7252875'
down_revision = '27c71b85bd07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_profile_id', sa.Integer(), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['student_profile_id'], ['student_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('student_profile_id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default so existing rows backfill to 0 instead of failing
        # the NOT NULL constraint -- the model's Python-side default=0 only
        # applies to new INSERTs through SQLAlchemy, not this ALTER TABLE.
        batch_op.add_column(
            sa.Column('free_turns_used', sa.Integer(), nullable=False, server_default='0')
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('free_turns_used')

    op.drop_table('subscriptions')
    # ### end Alembic commands ###
