"""add last_summarized_at to sessions

Revision ID: acce85c8816e
Revises: 415f3c2559aa
Create Date: 2026-08-06 22:22:58.335000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acce85c8816e'
down_revision = '415f3c2559aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_summarized_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('last_summarized_at')

    # ### end Alembic commands ###
