"""replace password auth with supabase external identity

Revision ID: b3482a27727b
Revises: 8192c7252875
Create Date: 2026-08-08 14:39:36.798650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3482a27727b'
down_revision = '8192c7252875'
branch_labels = None
depends_on = None


def upgrade():
    # Confirmed with the user: pre-launch, no real accounts -- only
    # password-auth test rows exist, safe to clear rather than backfill.
    # CASCADE also clears everything hanging off users (student_profiles
    # and, transitively, mastery/mistakes/sessions/messages/subscriptions).
    op.execute("TRUNCATE TABLE users CASCADE")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('external_auth_id', sa.String(length=36), nullable=False))
        batch_op.create_index(batch_op.f('ix_users_external_auth_id'), ['external_auth_id'], unique=True)
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # nullable=True, not the original NOT NULL -- there's no password hash
    # to reconstruct for rows created since the upgrade, so this is a
    # best-effort schema reversal, not a data-preserving one.
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_index(batch_op.f('ix_users_external_auth_id'))
        batch_op.drop_column('external_auth_id')

    # ### end Alembic commands ###
